fix syntax

diff --git a/.github/workflows/unit-tests.yml b/.github/workflows/unit-tests.yml
--- a/.github/workflows/unit-tests.yml
+++ b/.github/workflows/unit-tests.yml
@@ -44,7 +44,7 @@ jobs:
           echo
 
           echo "get status"
-          sudo /etc/init.d/mongodb status || { echo "(ignoring status failure, moving on)" }
+          sudo /etc/init.d/mongodb status || { echo "(ignoring status failure, moving on)"; }
           echo
 
           echo "try starting"
